// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Bloor Cannabis Dispensary",
  domain: "bloorcannabisdispensary.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "993 Bloor St W, Toronto, ON M6H 1M1",
  streetAddress: "993 Bloor St W",
  postalCode: "M6H 1M1",
  phone: "(437) 223-9353",
  phoneIntl: "+14372239353",
  neighborhood: "Bloor Street / West Toronto",
  nearbyAreas: ["Bloor Street", "Dufferin", "Dovercourt", "Bloorcourt", "Christie Pits", "Koreatown", "Ossington", "Bloordale Village"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/search/?api=1&query=993%20Bloor%20St%20W%2C%20Toronto%2C%20ON%20M6H%201M1",
  mapEmbedUrl: "https://maps.google.com/maps?q=Bloor%20Cannabis%20Dispensary%20993%20Bloor%20St%20W%2C%20Toronto%2C%20ON%20M6H%201M1&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6609278",
  longitude: "-79.4299091",
  hours: ["Mon-Thu: 11:00 AM - 11:00 PM", "Fri-Sat: 11:00 AM - 03:00 AM", "Sun: 11:00 AM - 11:00 PM"],
  seoTitle: "Bloor Cannabis Dispensary | Weed Dispensary in Toronto",
  metaDescription: "Bloor Cannabis Dispensary is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Bloor Street", "Dufferin", "Dovercourt"],
  introVariant: "If you are searching for a reliable weed dispensary in Toronto, Bloor Cannabis Dispensary at 993 Bloor St W is your go-to destination. We serve adults 19+ with a vast selection of weed products including cannabis flower, pre-rolls, edibles, THC vapes, shatter, and CBD oils. Serving customers near Bloor Street / West Toronto and surrounding communities like Dufferin, our cannabis store and weed shop is focused on quality and convenience.",
  neighborhoodDescription: "Located in the vibrant Bloor Street / West Toronto district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Bloor Street West and surrounding side streets",
  transitNote: "Conveniently located steps from Dufferin Station and served by local TTC bus and subway routes.",
  sectionTitle: "Serving Customers Near Bloor Street and West Toronto"
};
